/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedUploadBoletosRouteImport } from './routes/_authenticated/upload-boletos'
import { Route as AuthenticatedSepararComprovantesRouteImport } from './routes/_authenticated/separar-comprovantes'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedPermissoesRouteImport } from './routes/_authenticated/permissoes'
import { Route as AuthenticatedPagamentosManuaisRouteImport } from './routes/_authenticated/pagamentos-manuais'
import { Route as AuthenticatedPagamentosRouteImport } from './routes/_authenticated/pagamentos'
import { Route as AuthenticatedLogsRouteImport } from './routes/_authenticated/logs'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedEmpresasRouteImport } from './routes/_authenticated/empresas'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConversorOfxRouteImport } from './routes/_authenticated/conversor-ofx'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedBoletosRecebidosRouteImport } from './routes/_authenticated/boletos-recebidos'
import { Route as AuthenticatedFinanceiroRetornosRouteImport } from './routes/_authenticated/financeiro.retornos'
import { Route as AuthenticatedFinanceiroDocumentosRouteImport } from './routes/_authenticated/financeiro.documentos'
import { Route as AuthenticatedFinanceiroConfiguracoesBancariasRouteImport } from './routes/_authenticated/financeiro.configuracoes-bancarias'
import { Route as AuthenticatedFinanceiroCnabRouteImport } from './routes/_authenticated/financeiro.cnab'
import { Route as AuthenticatedFinanceiroDocumentosUploadRouteImport } from './routes/_authenticated/financeiro.documentos.upload'
import { Route as AuthenticatedFinanceiroDocumentosIdRouteImport } from './routes/_authenticated/financeiro.documentos.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUploadBoletosRoute =
  AuthenticatedUploadBoletosRouteImport.update({
    id: '/upload-boletos',
    path: '/upload-boletos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSepararComprovantesRoute =
  AuthenticatedSepararComprovantesRouteImport.update({
    id: '/separar-comprovantes',
    path: '/separar-comprovantes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPermissoesRoute = AuthenticatedPermissoesRouteImport.update({
  id: '/permissoes',
  path: '/permissoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPagamentosManuaisRoute =
  AuthenticatedPagamentosManuaisRouteImport.update({
    id: '/pagamentos-manuais',
    path: '/pagamentos-manuais',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPagamentosRoute = AuthenticatedPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLogsRoute = AuthenticatedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmpresasRoute = AuthenticatedEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConversorOfxRoute =
  AuthenticatedConversorOfxRouteImport.update({
    id: '/conversor-ofx',
    path: '/conversor-ofx',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBoletosRecebidosRoute =
  AuthenticatedBoletosRecebidosRouteImport.update({
    id: '/boletos-recebidos',
    path: '/boletos-recebidos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroRetornosRoute =
  AuthenticatedFinanceiroRetornosRouteImport.update({
    id: '/retornos',
    path: '/retornos',
    getParentRoute: () => AuthenticatedFinanceiroRoute,
  } as any)
const AuthenticatedFinanceiroDocumentosRoute =
  AuthenticatedFinanceiroDocumentosRouteImport.update({
    id: '/documentos',
    path: '/documentos',
    getParentRoute: () => AuthenticatedFinanceiroRoute,
  } as any)
const AuthenticatedFinanceiroConfiguracoesBancariasRoute =
  AuthenticatedFinanceiroConfiguracoesBancariasRouteImport.update({
    id: '/configuracoes-bancarias',
    path: '/configuracoes-bancarias',
    getParentRoute: () => AuthenticatedFinanceiroRoute,
  } as any)
const AuthenticatedFinanceiroCnabRoute =
  AuthenticatedFinanceiroCnabRouteImport.update({
    id: '/cnab',
    path: '/cnab',
    getParentRoute: () => AuthenticatedFinanceiroRoute,
  } as any)
const AuthenticatedFinanceiroDocumentosUploadRoute =
  AuthenticatedFinanceiroDocumentosUploadRouteImport.update({
    id: '/upload',
    path: '/upload',
    getParentRoute: () => AuthenticatedFinanceiroDocumentosRoute,
  } as any)
const AuthenticatedFinanceiroDocumentosIdRoute =
  AuthenticatedFinanceiroDocumentosIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedFinanceiroDocumentosRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/boletos-recebidos': typeof AuthenticatedBoletosRecebidosRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/conversor-ofx': typeof AuthenticatedConversorOfxRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/empresas': typeof AuthenticatedEmpresasRoute
  '/financeiro': typeof AuthenticatedFinanceiroRouteWithChildren
  '/historico': typeof AuthenticatedHistoricoRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/pagamentos': typeof AuthenticatedPagamentosRoute
  '/pagamentos-manuais': typeof AuthenticatedPagamentosManuaisRoute
  '/permissoes': typeof AuthenticatedPermissoesRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/separar-comprovantes': typeof AuthenticatedSepararComprovantesRoute
  '/upload-boletos': typeof AuthenticatedUploadBoletosRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/financeiro/cnab': typeof AuthenticatedFinanceiroCnabRoute
  '/financeiro/configuracoes-bancarias': typeof AuthenticatedFinanceiroConfiguracoesBancariasRoute
  '/financeiro/documentos': typeof AuthenticatedFinanceiroDocumentosRouteWithChildren
  '/financeiro/retornos': typeof AuthenticatedFinanceiroRetornosRoute
  '/financeiro/documentos/$id': typeof AuthenticatedFinanceiroDocumentosIdRoute
  '/financeiro/documentos/upload': typeof AuthenticatedFinanceiroDocumentosUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/boletos-recebidos': typeof AuthenticatedBoletosRecebidosRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/conversor-ofx': typeof AuthenticatedConversorOfxRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/empresas': typeof AuthenticatedEmpresasRoute
  '/financeiro': typeof AuthenticatedFinanceiroRouteWithChildren
  '/historico': typeof AuthenticatedHistoricoRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/pagamentos': typeof AuthenticatedPagamentosRoute
  '/pagamentos-manuais': typeof AuthenticatedPagamentosManuaisRoute
  '/permissoes': typeof AuthenticatedPermissoesRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/separar-comprovantes': typeof AuthenticatedSepararComprovantesRoute
  '/upload-boletos': typeof AuthenticatedUploadBoletosRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/financeiro/cnab': typeof AuthenticatedFinanceiroCnabRoute
  '/financeiro/configuracoes-bancarias': typeof AuthenticatedFinanceiroConfiguracoesBancariasRoute
  '/financeiro/documentos': typeof AuthenticatedFinanceiroDocumentosRouteWithChildren
  '/financeiro/retornos': typeof AuthenticatedFinanceiroRetornosRoute
  '/financeiro/documentos/$id': typeof AuthenticatedFinanceiroDocumentosIdRoute
  '/financeiro/documentos/upload': typeof AuthenticatedFinanceiroDocumentosUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/boletos-recebidos': typeof AuthenticatedBoletosRecebidosRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/conversor-ofx': typeof AuthenticatedConversorOfxRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/empresas': typeof AuthenticatedEmpresasRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRouteWithChildren
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/logs': typeof AuthenticatedLogsRoute
  '/_authenticated/pagamentos': typeof AuthenticatedPagamentosRoute
  '/_authenticated/pagamentos-manuais': typeof AuthenticatedPagamentosManuaisRoute
  '/_authenticated/permissoes': typeof AuthenticatedPermissoesRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/separar-comprovantes': typeof AuthenticatedSepararComprovantesRoute
  '/_authenticated/upload-boletos': typeof AuthenticatedUploadBoletosRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/financeiro/cnab': typeof AuthenticatedFinanceiroCnabRoute
  '/_authenticated/financeiro/configuracoes-bancarias': typeof AuthenticatedFinanceiroConfiguracoesBancariasRoute
  '/_authenticated/financeiro/documentos': typeof AuthenticatedFinanceiroDocumentosRouteWithChildren
  '/_authenticated/financeiro/retornos': typeof AuthenticatedFinanceiroRetornosRoute
  '/_authenticated/financeiro/documentos/$id': typeof AuthenticatedFinanceiroDocumentosIdRoute
  '/_authenticated/financeiro/documentos/upload': typeof AuthenticatedFinanceiroDocumentosUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/boletos-recebidos'
    | '/configuracoes'
    | '/conversor-ofx'
    | '/dashboard'
    | '/empresas'
    | '/financeiro'
    | '/historico'
    | '/logs'
    | '/pagamentos'
    | '/pagamentos-manuais'
    | '/permissoes'
    | '/relatorios'
    | '/separar-comprovantes'
    | '/upload-boletos'
    | '/usuarios'
    | '/financeiro/cnab'
    | '/financeiro/configuracoes-bancarias'
    | '/financeiro/documentos'
    | '/financeiro/retornos'
    | '/financeiro/documentos/$id'
    | '/financeiro/documentos/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/boletos-recebidos'
    | '/configuracoes'
    | '/conversor-ofx'
    | '/dashboard'
    | '/empresas'
    | '/financeiro'
    | '/historico'
    | '/logs'
    | '/pagamentos'
    | '/pagamentos-manuais'
    | '/permissoes'
    | '/relatorios'
    | '/separar-comprovantes'
    | '/upload-boletos'
    | '/usuarios'
    | '/financeiro/cnab'
    | '/financeiro/configuracoes-bancarias'
    | '/financeiro/documentos'
    | '/financeiro/retornos'
    | '/financeiro/documentos/$id'
    | '/financeiro/documentos/upload'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/boletos-recebidos'
    | '/_authenticated/configuracoes'
    | '/_authenticated/conversor-ofx'
    | '/_authenticated/dashboard'
    | '/_authenticated/empresas'
    | '/_authenticated/financeiro'
    | '/_authenticated/historico'
    | '/_authenticated/logs'
    | '/_authenticated/pagamentos'
    | '/_authenticated/pagamentos-manuais'
    | '/_authenticated/permissoes'
    | '/_authenticated/relatorios'
    | '/_authenticated/separar-comprovantes'
    | '/_authenticated/upload-boletos'
    | '/_authenticated/usuarios'
    | '/_authenticated/financeiro/cnab'
    | '/_authenticated/financeiro/configuracoes-bancarias'
    | '/_authenticated/financeiro/documentos'
    | '/_authenticated/financeiro/retornos'
    | '/_authenticated/financeiro/documentos/$id'
    | '/_authenticated/financeiro/documentos/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/upload-boletos': {
      id: '/_authenticated/upload-boletos'
      path: '/upload-boletos'
      fullPath: '/upload-boletos'
      preLoaderRoute: typeof AuthenticatedUploadBoletosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/separar-comprovantes': {
      id: '/_authenticated/separar-comprovantes'
      path: '/separar-comprovantes'
      fullPath: '/separar-comprovantes'
      preLoaderRoute: typeof AuthenticatedSepararComprovantesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/permissoes': {
      id: '/_authenticated/permissoes'
      path: '/permissoes'
      fullPath: '/permissoes'
      preLoaderRoute: typeof AuthenticatedPermissoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pagamentos-manuais': {
      id: '/_authenticated/pagamentos-manuais'
      path: '/pagamentos-manuais'
      fullPath: '/pagamentos-manuais'
      preLoaderRoute: typeof AuthenticatedPagamentosManuaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pagamentos': {
      id: '/_authenticated/pagamentos'
      path: '/pagamentos'
      fullPath: '/pagamentos'
      preLoaderRoute: typeof AuthenticatedPagamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logs': {
      id: '/_authenticated/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthenticatedLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/empresas': {
      id: '/_authenticated/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof AuthenticatedEmpresasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conversor-ofx': {
      id: '/_authenticated/conversor-ofx'
      path: '/conversor-ofx'
      fullPath: '/conversor-ofx'
      preLoaderRoute: typeof AuthenticatedConversorOfxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/boletos-recebidos': {
      id: '/_authenticated/boletos-recebidos'
      path: '/boletos-recebidos'
      fullPath: '/boletos-recebidos'
      preLoaderRoute: typeof AuthenticatedBoletosRecebidosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/retornos': {
      id: '/_authenticated/financeiro/retornos'
      path: '/retornos'
      fullPath: '/financeiro/retornos'
      preLoaderRoute: typeof AuthenticatedFinanceiroRetornosRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRoute
    }
    '/_authenticated/financeiro/documentos': {
      id: '/_authenticated/financeiro/documentos'
      path: '/documentos'
      fullPath: '/financeiro/documentos'
      preLoaderRoute: typeof AuthenticatedFinanceiroDocumentosRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRoute
    }
    '/_authenticated/financeiro/configuracoes-bancarias': {
      id: '/_authenticated/financeiro/configuracoes-bancarias'
      path: '/configuracoes-bancarias'
      fullPath: '/financeiro/configuracoes-bancarias'
      preLoaderRoute: typeof AuthenticatedFinanceiroConfiguracoesBancariasRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRoute
    }
    '/_authenticated/financeiro/cnab': {
      id: '/_authenticated/financeiro/cnab'
      path: '/cnab'
      fullPath: '/financeiro/cnab'
      preLoaderRoute: typeof AuthenticatedFinanceiroCnabRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRoute
    }
    '/_authenticated/financeiro/documentos/upload': {
      id: '/_authenticated/financeiro/documentos/upload'
      path: '/upload'
      fullPath: '/financeiro/documentos/upload'
      preLoaderRoute: typeof AuthenticatedFinanceiroDocumentosUploadRouteImport
      parentRoute: typeof AuthenticatedFinanceiroDocumentosRoute
    }
    '/_authenticated/financeiro/documentos/$id': {
      id: '/_authenticated/financeiro/documentos/$id'
      path: '/$id'
      fullPath: '/financeiro/documentos/$id'
      preLoaderRoute: typeof AuthenticatedFinanceiroDocumentosIdRouteImport
      parentRoute: typeof AuthenticatedFinanceiroDocumentosRoute
    }
  }
}

interface AuthenticatedFinanceiroDocumentosRouteChildren {
  AuthenticatedFinanceiroDocumentosIdRoute: typeof AuthenticatedFinanceiroDocumentosIdRoute
  AuthenticatedFinanceiroDocumentosUploadRoute: typeof AuthenticatedFinanceiroDocumentosUploadRoute
}

const AuthenticatedFinanceiroDocumentosRouteChildren: AuthenticatedFinanceiroDocumentosRouteChildren =
  {
    AuthenticatedFinanceiroDocumentosIdRoute:
      AuthenticatedFinanceiroDocumentosIdRoute,
    AuthenticatedFinanceiroDocumentosUploadRoute:
      AuthenticatedFinanceiroDocumentosUploadRoute,
  }

const AuthenticatedFinanceiroDocumentosRouteWithChildren =
  AuthenticatedFinanceiroDocumentosRoute._addFileChildren(
    AuthenticatedFinanceiroDocumentosRouteChildren,
  )

interface AuthenticatedFinanceiroRouteChildren {
  AuthenticatedFinanceiroCnabRoute: typeof AuthenticatedFinanceiroCnabRoute
  AuthenticatedFinanceiroConfiguracoesBancariasRoute: typeof AuthenticatedFinanceiroConfiguracoesBancariasRoute
  AuthenticatedFinanceiroDocumentosRoute: typeof AuthenticatedFinanceiroDocumentosRouteWithChildren
  AuthenticatedFinanceiroRetornosRoute: typeof AuthenticatedFinanceiroRetornosRoute
}

const AuthenticatedFinanceiroRouteChildren: AuthenticatedFinanceiroRouteChildren =
  {
    AuthenticatedFinanceiroCnabRoute: AuthenticatedFinanceiroCnabRoute,
    AuthenticatedFinanceiroConfiguracoesBancariasRoute:
      AuthenticatedFinanceiroConfiguracoesBancariasRoute,
    AuthenticatedFinanceiroDocumentosRoute:
      AuthenticatedFinanceiroDocumentosRouteWithChildren,
    AuthenticatedFinanceiroRetornosRoute: AuthenticatedFinanceiroRetornosRoute,
  }

const AuthenticatedFinanceiroRouteWithChildren =
  AuthenticatedFinanceiroRoute._addFileChildren(
    AuthenticatedFinanceiroRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBoletosRecebidosRoute: typeof AuthenticatedBoletosRecebidosRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedConversorOfxRoute: typeof AuthenticatedConversorOfxRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmpresasRoute: typeof AuthenticatedEmpresasRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRouteWithChildren
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedLogsRoute: typeof AuthenticatedLogsRoute
  AuthenticatedPagamentosRoute: typeof AuthenticatedPagamentosRoute
  AuthenticatedPagamentosManuaisRoute: typeof AuthenticatedPagamentosManuaisRoute
  AuthenticatedPermissoesRoute: typeof AuthenticatedPermissoesRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedSepararComprovantesRoute: typeof AuthenticatedSepararComprovantesRoute
  AuthenticatedUploadBoletosRoute: typeof AuthenticatedUploadBoletosRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBoletosRecebidosRoute: AuthenticatedBoletosRecebidosRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedConversorOfxRoute: AuthenticatedConversorOfxRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmpresasRoute: AuthenticatedEmpresasRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRouteWithChildren,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedLogsRoute: AuthenticatedLogsRoute,
  AuthenticatedPagamentosRoute: AuthenticatedPagamentosRoute,
  AuthenticatedPagamentosManuaisRoute: AuthenticatedPagamentosManuaisRoute,
  AuthenticatedPermissoesRoute: AuthenticatedPermissoesRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedSepararComprovantesRoute: AuthenticatedSepararComprovantesRoute,
  AuthenticatedUploadBoletosRoute: AuthenticatedUploadBoletosRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
